
name: Build with sonar_cloud

on: [pull_request, workflow_dispatch]

jobs:
  my-workflow-job-3:
    name: my-workflow-job-3
    runs-on: ubuntu-latest
    environment: sonar


    steps:
      - name: echo sonar token
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PROJ_MGT_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo ${{secrets.SONAR_TOKEN }}
      
      - name: echo sonar token
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PROJ_MGT_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo ${{secrets.PROJ_MGT_TOKEN }}
